use rustc_hash::FxHashSet;

use zutai_tlc::{BuiltinOp, PrimTy, TlcExpr, TlcExprId, TlcTupleItem, TlcType};

use crate::{DfArm, DfBuiltinOp, DfNodeKind, DfTupleNodeItem, NodeId};

use super::*;

impl<'m> Lowerer<'m> {
    // ── Expression lowering ───────────────────────────────────────────────────

    pub(super) fn lower_expr(&mut self, id: TlcExprId) -> NodeId {
        let expr = self.module.expr_arena[id].clone();
        let span = self.module.spans.get(&id).copied();
        let df_ty = match self.module.expr_types.get(&id).copied() {
            Some(t) => self.lower_type(t),
            None => self.error_ty,
        };

        match expr {
            TlcExpr::Var(binding) => {
                // Local env first — this is where sharing happens.
                if let Some(&node_id) = self.local_env.get(&binding) {
                    return node_id;
                }
                // Global reference.
                if let Some(name) = self.global_names.get(&binding).cloned() {
                    return self.alloc_node(DfNodeKind::GlobalRef(name), df_ty, span);
                }
                self.alloc_node(DfNodeKind::Error, self.error_ty, span)
            }

            TlcExpr::Lit(lit) => match lower_lit(&lit) {
                Some(df_lit) => self.alloc_node(DfNodeKind::Lit(df_lit), df_ty, span),
                None => self.alloc_node(DfNodeKind::Error, self.error_ty, span),
            },

            TlcExpr::Lam(param_binding, param_ty, body) => {
                let param_df_ty = self.lower_type(param_ty);
                let bind_node = self.alloc_node(DfNodeKind::Bind, param_df_ty, None);
                self.local_env.insert(param_binding, bind_node);
                let body_node = self.lower_expr(body);
                self.local_env.remove(&param_binding);
                self.alloc_node(
                    DfNodeKind::Lambda {
                        param: bind_node,
                        body: body_node,
                    },
                    df_ty,
                    span,
                )
            }

            TlcExpr::App(func, arg) => {
                let func_node = self.lower_expr(func);
                let arg_node = self.lower_expr(arg);
                self.alloc_node(
                    DfNodeKind::Apply {
                        func: func_node,
                        arg: arg_node,
                    },
                    df_ty,
                    span,
                )
            }

            TlcExpr::TyLam(tyvar, _kind, body) => {
                let body_node = self.lower_expr(body);
                self.alloc_node(
                    DfNodeKind::TyLam {
                        ty_params: vec![lower_tyvar(tyvar)],
                        body: body_node,
                    },
                    df_ty,
                    span,
                )
            }

            TlcExpr::TyApp(expr, ty_arg) => {
                let poly_node = self.lower_expr(expr);
                let df_ty_arg = self.lower_type(ty_arg);
                self.alloc_node(
                    DfNodeKind::TyApp {
                        poly: poly_node,
                        ty_args: vec![df_ty_arg],
                    },
                    df_ty,
                    span,
                )
            }

            TlcExpr::Let {
                binding,
                ty: _,
                value,
                body,
            } => {
                // Tree-to-graph: lower value once, register its NodeId.
                // All references to `binding` in `body` will reuse this NodeId directly.
                let value_node = self.lower_expr(value);
                self.local_env.insert(binding, value_node);
                let body_node = self.lower_expr(body);
                self.local_env.remove(&binding);
                // The `let` itself disappears; graph edges carry the sharing.
                body_node
            }

            TlcExpr::Letrec { bindings, body } => {
                // TlcExpr::Letrec is defined in the IR but never generated by the v0 TLC
                // lowerer. Lower defensively without mutual visibility: each binding's value
                // is lowered before the next binding's name is in scope (not true letrec
                // semantics). This is acceptable because this code path is unreachable in
                // well-formed v0 programs; the ANF phase handles recursion via GlobalRef SCC
                // analysis on globals, not via local letrec.
                for (binding, _, value_id) in &bindings {
                    let value_node = self.lower_expr(*value_id);
                    self.local_env.insert(*binding, value_node);
                }
                let body_node = self.lower_expr(body);
                for (binding, _, _) in &bindings {
                    self.local_env.remove(binding);
                }
                body_node
            }

            TlcExpr::Case(scrutinee, alts) => {
                // Resolve the scrutinee's type so arm-bound variables get the right Bind type.
                let scrutinee_df_ty = self
                    .module
                    .expr_types
                    .get(&scrutinee)
                    .copied()
                    .map(|t| self.lower_type(t))
                    .unwrap_or(self.error_ty);
                let scrutinee_node = self.lower_expr(scrutinee);
                let arms: Vec<DfArm> = alts
                    .iter()
                    .map(|alt| self.lower_alt(alt, scrutinee_df_ty))
                    .collect();
                self.alloc_node(
                    DfNodeKind::Match {
                        scrutinee: scrutinee_node,
                        arms,
                    },
                    df_ty,
                    span,
                )
            }

            TlcExpr::Record(fields) => {
                let mut df_fields: Vec<(String, NodeId)> = fields
                    .iter()
                    .map(|(name, expr_id)| (name.clone(), self.lower_expr(*expr_id)))
                    .collect();
                df_fields.sort_by(|a, b| a.0.cmp(&b.0));
                self.alloc_node(DfNodeKind::Record(df_fields), df_ty, span)
            }

            TlcExpr::RecordUpdate { receiver, fields } => {
                let base = self.lower_expr(receiver);
                let result_ty = self.module.expr_types.get(&id).copied();
                let updates: Vec<(String, usize, NodeId)> = fields
                    .iter()
                    .map(|(name, expr_id)| {
                        let value = self.lower_expr(*expr_id);
                        let slot = result_ty
                            .and_then(|ty| {
                                self.record_slot_for_tlc_type(ty, name, &mut FxHashSet::default())
                            })
                            .or_else(|| self.record_slot_for_df_ty(df_ty, name))
                            .unwrap_or(0);
                        (name.clone(), slot, value)
                    })
                    .collect();
                self.alloc_node(DfNodeKind::RecordUpdate { base, updates }, df_ty, span)
            }

            TlcExpr::GetField(expr, field) => {
                let slot = self
                    .module
                    .dict_field_slots
                    .get(&id)
                    .copied()
                    .or_else(|| self.record_slot_for_expr_type(expr, &field))
                    .unwrap_or(0);
                let base_node = self.lower_expr(expr);
                self.alloc_node(
                    DfNodeKind::Select {
                        base: base_node,
                        field,
                        slot,
                    },
                    df_ty,
                    span,
                )
            }

            TlcExpr::Tuple(items) => {
                let df_items: Vec<DfTupleNodeItem> = items
                    .iter()
                    .map(|item| match item {
                        TlcTupleItem::Named { name, value } => DfTupleNodeItem::Named {
                            name: name.clone(),
                            value: self.lower_expr(*value),
                        },
                        TlcTupleItem::Positional(v) => {
                            DfTupleNodeItem::Positional(self.lower_expr(*v))
                        }
                    })
                    .collect();
                self.alloc_node(DfNodeKind::Tuple(df_items), df_ty, span)
            }

            TlcExpr::List(items) => {
                let df_items: Vec<NodeId> = items.iter().map(|&e| self.lower_expr(e)).collect();
                self.alloc_node(DfNodeKind::List(df_items), df_ty, span)
            }

            TlcExpr::Builtin(op, lhs, rhs) => {
                let lhs_node = self.lower_expr(lhs);
                let rhs_node = self.lower_expr(rhs);
                if op == BuiltinOp::Coalesce {
                    self.alloc_node(
                        DfNodeKind::Coalesce {
                            value: lhs_node,
                            fallback: rhs_node,
                        },
                        df_ty,
                        span,
                    )
                } else {
                    let df_op = self
                        .lower_posit_builtin_op(op, lhs)
                        .unwrap_or_else(|| lower_builtin_op(op));
                    self.alloc_node(DfNodeKind::Builtin(df_op, lhs_node, rhs_node), df_ty, span)
                }
            }

            TlcExpr::Variant(tag, payload) => {
                let payload_node = self.lower_expr(payload);
                let tag_index = self.variant_tag_index_for_df_ty(df_ty, &tag);
                self.alloc_node(
                    DfNodeKind::Variant {
                        tag,
                        tag_index,
                        value: payload_node,
                    },
                    df_ty,
                    span,
                )
            }

            TlcExpr::Import(source) => {
                // `.zti` data imports resolved by the front end lower inline to a
                // Dataflow Core constant. `.zt` imports (and any unresolved `.zti`)
                // fall through to an `Import` node, which the lowering gate rejects.
                if is_zti_import(&source)
                    && let Some(value) = self.imports.zti.get(&source)
                {
                    let value = *value;
                    return self.lower_immediate(value, df_ty);
                }
                let (path, kind) = lower_import_source(&source);
                self.alloc_node(DfNodeKind::Import { path, kind }, df_ty, span)
            }

            TlcExpr::Sequence(items) => {
                let nodes = items
                    .into_iter()
                    .map(|item| self.lower_expr(item))
                    .collect::<Vec<_>>();
                if nodes.is_empty() {
                    self.alloc_node(DfNodeKind::Error, self.error_ty, span)
                } else {
                    self.alloc_node(DfNodeKind::Sequence(nodes), df_ty, span)
                }
            }

            TlcExpr::Perform { op, arg } => match zutai_tlc::HostOp::from_name(&op) {
                Some(zutai_tlc::HostOp::IoPrint) => {
                    let arg = self.lower_expr(arg);
                    self.alloc_node(DfNodeKind::HostPrint { arg }, df_ty, span)
                }
                Some(op) => {
                    let arg = self.lower_expr(arg);
                    self.alloc_node(DfNodeKind::HostOp { op, arg }, df_ty, span)
                }
                None => self.alloc_node(DfNodeKind::Error, self.error_ty, span),
            },

            TlcExpr::Handle { .. } | TlcExpr::Resume { .. } => {
                self.alloc_node(DfNodeKind::Error, self.error_ty, span)
            }
        }
    }

    pub(super) fn lower_posit_builtin_op(
        &self,
        op: BuiltinOp,
        lhs: TlcExprId,
    ) -> Option<DfBuiltinOp> {
        let ty = self.module.expr_types.get(&lhs)?;
        let TlcType::Prim(PrimTy::Posit(spec)) = self.module.type_arena[*ty] else {
            return None;
        };
        let op = lower_posit_op(op)?;
        Some(DfBuiltinOp::Posit { op, spec })
    }
}
